@startuml
'https://plantuml.com/class-diagram


+class Boss extends Bricks {
    - int hitCounter
    - final Image bossSprite
    - final int bossPosX
    - boolean activeWeapon
    - BossWeapon bossWeapon

    + Boss()
    + int getHitCounter()
    + Image getBossSprite()
    + BossWeapon getBossWeapon()
    + getBrickPosX():int
    + setDestroy(boolean destroy) : void
    +  isDestroy():boolean
    + setHitCounter(int hitCounter) :void
}

@enduml